openapi: 3.0.1
info:
  title: AI Testimonials
  description: API for generating fake testimonials
  version: 1.1.0
schemes:
- https
produces:
- application/json
paths:
  /api/v1/ai-testimonials/generate:
    post:
      tags:
        - AiTestimonialsApi
      parameters:
        - name: OPENAI_KEY
          in: header
          style: simple
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestimonialInput'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Identity'
  /api/v1/ai-testimonials/redo:
    post:
      tags:
        - AiTestimonialsApi
      parameters:
        - name: id
          in: query
          required: true
          style: form
          schema:
            type: string
      responses:
        '200':
          description: OK
  /api/v1/ai-testimonials/save:
    post:
      tags:
        - AiTestimonialsApi
      parameters:
        - name: id
          in: query
          required: true
          style: form
          schema:
            type: string
      responses:
        '200':
          description: OK
  /api/v1/ai-testimonials:
    get:
      tags:
        - AiTestimonialsApi
      parameters:
        - name: id
          in: query
          style: form
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TestimonialResult'
components:
  schemas:
    Identity:
      type: object
      properties:
        id:
          type: string
          nullable: true
      additionalProperties: false
    TestimonialInput:
      type: object
      properties:
        name:
          type: string
          nullable: true
        skills:
          type: string
          nullable: true
      additionalProperties: false
    TestimonialResult:
      type: object
      properties:
        testimonial:
          type: string
          nullable: true
        testifierName:
          type: string
          nullable: true
        testifierCompany:
          type: string
          nullable: true
        testifierPosition:
          type: string
          nullable: true
        logoUrl:
          type: string
          nullable: true
        logoB64:
          type: string
          nullable: true
      additionalProperties: false
  securitySchemes:
    API_KEY:
      type: apiKey
      description: ApiKey must appear in header
      name: x-api-key
      in: header
security:
  - API_KEY: [ ]